# Generated by Django 5.2.8 on 2025-11-28 10:07

import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerimage',
            name='image',
            field=models.ImageField(upload_to='banner_images/', validators=[main.validators.validate_image]),
        ),
        migrations.AlterField(
            model_name='course',
            name='banner',
            field=models.ImageField(upload_to='course_banners/', validators=[main.validators.validate_image]),
        ),
        migrations.AlterField(
            model_name='course',
            name='logo',
            field=models.ImageField(upload_to='course_logos/', validators=[main.validators.validate_image]),
        ),
        migrations.AlterField(
            model_name='courseicon',
            name='icon',
            field=models.ImageField(upload_to='course_icons/', validators=[main.validators.validate_image]),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(upload_to='partners/', validators=[main.validators.validate_image]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(upload_to='teacher_photos/', validators=[main.validators.validate_image]),
        ),
    ]
